GET http://localhost:7878/games

###

POST http://localhost:7878/games/launch
Content-Type: application/json

{
    "source": "gog",
    "id": "HKLM\\1207658995_is1"
}

###
GET http://localhost:7878/games/running
