GET http://localhost:7878/games

###

POST http://localhost:7878/games/launch
Content-Type: application/json

{
    "id": "dc9d2e595d0e4650b35d659f90d41059"
}

###
GET http://localhost:7878/games/running

###
GET http://localhost:7878/windows

